### ISSUE TITLE
New windows do not appear in overview

### ISSUE THREAD

**Issue by tsammut** [amiller27/OverviewAllWindows#3]
Hi. Thanks again for creating this extension--it is great.

While this extension is in use, if a window is created while viewing the overview, it does not show up in the overview. There are two easy ways to see this behavior:
- While viewing the overview, use a custom hotkey to launch an application. I have custom hotkeys for 'new terminal', chromium, etc. If I am in the overview and use the hotkey, the window opens as expected but is not shown in the overview. 
- Open a gnome-terminal and run the command 'sleep 5 && gnome-terminal' and then immediately switch to the overview mode. A new gnome-terminal will open after 5 seconds, but will not be shown in the overview. 

FWIW, I also have the workspaces-to-dock extension installed and I can see the windows open in the workspace thumbnails, and of course the new windows are there when I exit the overview mode. 

Please let me know if you have any questions!

**Comment by fawtytoo** [comment]
Over 2 years later and this is still an issue on Gnome 3.22.2

**Comment by amiller27** [comment]
This should be fixed on current master, you can try it out there or wait until it's updated on extensions.gnome.org.  For future reference, if you're really bent out of shape about something like this that hasn't been fixed in a while, it's often helpful to look into fixing it yourself and making a PR.  Often the reason it hasn't been fixed is that the original author isn't actively maintaining it, as was the case here.
